
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Dona Joana",
    "email": "joana@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "15b6eee5-4140-4755-9578-9e53a9c10fca"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "0e96d032-86fd-11ec-8b22-9a5ce86758a4",
    "account_id_to": "534b6b56-a988-11ec-b7e0-2b8e9696da41",
    "amount": 2
}